// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.debuggersight.hubspot_mobile_chat

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Permission-state keys defined by the HubSpot SDKs. The Dart facade maps each
 * value to the SDK's string key.
 */
enum class ChatPropertyKey(val raw: Int) {
  CAMERA_PERMISSIONS(0),
  PHOTO_PERMISSIONS(1),
  NOTIFICATION_PERMISSIONS(2),
  LOCATION_PERMISSIONS(3);

  companion object {
    fun ofRaw(raw: Int): ChatPropertyKey? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Incoming chat push payload. native -> Dart on receipt; Dart -> native into
 * [HubspotHostApi.openChat] when a notification is tapped.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PushData (
  val messageId: String? = null,
  val threadId: String? = null,
  val raw: Map<String?, String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PushData {
      val messageId = pigeonVar_list[0] as String?
      val threadId = pigeonVar_list[1] as String?
      val raw = pigeonVar_list[2] as Map<String?, String?>?
      return PushData(messageId, threadId, raw)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      messageId,
      threadId,
      raw,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ChatPropertyKey.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ChatPropertyKey -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is PushData -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart -> native. Implemented by the Kotlin/Swift plugin classes, which forward
 * to the native HubspotManager. Holds zero logic on the Dart side.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HubspotHostApi {
  /** Initialize the SDK from the bundled config file. Throws on missing/invalid config. */
  fun configure(callback: (Result<Unit>) -> Unit)
  /** Associate the chat session with a HubSpot contact. Pass-through token. */
  fun setUserIdentity(email: String, identityToken: String, callback: (Result<Unit>) -> Unit)
  /** Set custom chat properties for the current app session. */
  fun setChatProperties(properties: Map<String, String>, callback: (Result<Unit>) -> Unit)
  /**
   * Present the HubSpot chat UI. Optional [chatFlow] targets a flow; optional
   * [pushData] opens the conversation referenced by a tapped notification.
   */
  fun openChat(chatFlow: String?, pushData: PushData?, callback: (Result<Unit>) -> Unit)
  /** Forward an app-obtained FCM/APNs token to the SDK. */
  fun registerPushToken(token: String, callback: (Result<Unit>) -> Unit)
  /** Clear stored identity and properties for future sessions. */
  fun logout(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by HubspotHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `HubspotHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HubspotHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.configure{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.setUserIdentity$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val emailArg = args[0] as String
            val identityTokenArg = args[1] as String
            api.setUserIdentity(emailArg, identityTokenArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.setChatProperties$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val propertiesArg = args[0] as Map<String, String>
            api.setChatProperties(propertiesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.openChat$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val chatFlowArg = args[0] as String?
            val pushDataArg = args[1] as PushData?
            api.openChat(chatFlowArg, pushDataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.registerPushToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as String
            api.registerPushToken(tokenArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.logout$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.logout{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * native -> Dart. The plugin invokes this; the Dart facade republishes it as a
 * `Stream<PushData>`.
 *
 * Generated class from Pigeon that represents Flutter messages that can be called from Kotlin.
 */
class HubspotFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by HubspotFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onNewMessagePush(dataArg: PushData, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.hubspot_mobile_chat.HubspotFlutterApi.onNewMessagePush$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(dataArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
