// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Permission-state keys defined by the HubSpot SDKs. The Dart facade maps each
/// value to the SDK's string key.
enum ChatPropertyKey: Int {
  case cameraPermissions = 0
  case photoPermissions = 1
  case notificationPermissions = 2
  case locationPermissions = 3
}

/// Incoming chat push payload. native -> Dart on receipt; Dart -> native into
/// [HubspotHostApi.openChat] when a notification is tapped.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PushData {
  var messageId: String? = nil
  var threadId: String? = nil
  var raw: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PushData? {
    let messageId: String? = nilOrValue(pigeonVar_list[0])
    let threadId: String? = nilOrValue(pigeonVar_list[1])
    let raw: [String?: String?]? = nilOrValue(pigeonVar_list[2])

    return PushData(
      messageId: messageId,
      threadId: threadId,
      raw: raw
    )
  }
  func toList() -> [Any?] {
    return [
      messageId,
      threadId,
      raw,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ChatPropertyKey(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return PushData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ChatPropertyKey {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PushData {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Dart -> native. Implemented by the Kotlin/Swift plugin classes, which forward
/// to the native HubspotManager. Holds zero logic on the Dart side.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HubspotHostApi {
  /// Initialize the SDK from the bundled config file. Throws on missing/invalid config.
  func configure(completion: @escaping (Result<Void, Error>) -> Void)
  /// Associate the chat session with a HubSpot contact. Pass-through token.
  func setUserIdentity(email: String, identityToken: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Set custom chat properties for the current app session.
  func setChatProperties(properties: [String: String], completion: @escaping (Result<Void, Error>) -> Void)
  /// Present the HubSpot chat UI. Optional [chatFlow] targets a flow; optional
  /// [pushData] opens the conversation referenced by a tapped notification.
  func openChat(chatFlow: String?, pushData: PushData?, completion: @escaping (Result<Void, Error>) -> Void)
  /// Forward an app-obtained FCM/APNs token to the SDK.
  func registerPushToken(token: String, completion: @escaping (Result<Void, Error>) -> Void)
  /// Clear stored identity and properties for future sessions.
  func logout(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HubspotHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `HubspotHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HubspotHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Initialize the SDK from the bundled config file. Throws on missing/invalid config.
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { _, reply in
        api.configure { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    /// Associate the chat session with a HubSpot contact. Pass-through token.
    let setUserIdentityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.setUserIdentity\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUserIdentityChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let emailArg = args[0] as! String
        let identityTokenArg = args[1] as! String
        api.setUserIdentity(email: emailArg, identityToken: identityTokenArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setUserIdentityChannel.setMessageHandler(nil)
    }
    /// Set custom chat properties for the current app session.
    let setChatPropertiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.setChatProperties\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setChatPropertiesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let propertiesArg = args[0] as! [String: String]
        api.setChatProperties(properties: propertiesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setChatPropertiesChannel.setMessageHandler(nil)
    }
    /// Present the HubSpot chat UI. Optional [chatFlow] targets a flow; optional
    /// [pushData] opens the conversation referenced by a tapped notification.
    let openChatChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.openChat\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openChatChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let chatFlowArg: String? = nilOrValue(args[0])
        let pushDataArg: PushData? = nilOrValue(args[1])
        api.openChat(chatFlow: chatFlowArg, pushData: pushDataArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openChatChannel.setMessageHandler(nil)
    }
    /// Forward an app-obtained FCM/APNs token to the SDK.
    let registerPushTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.registerPushToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerPushTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let tokenArg = args[0] as! String
        api.registerPushToken(token: tokenArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerPushTokenChannel.setMessageHandler(nil)
    }
    /// Clear stored identity and properties for future sessions.
    let logoutChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.hubspot_mobile_chat.HubspotHostApi.logout\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logoutChannel.setMessageHandler { _, reply in
        api.logout { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      logoutChannel.setMessageHandler(nil)
    }
  }
}
/// native -> Dart. The plugin invokes this; the Dart facade republishes it as a
/// `Stream<PushData>`.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol HubspotFlutterApiProtocol {
  func onNewMessagePush(data dataArg: PushData, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class HubspotFlutterApi: HubspotFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onNewMessagePush(data dataArg: PushData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.hubspot_mobile_chat.HubspotFlutterApi.onNewMessagePush\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
